### ISSUE TITLE
Need Use-Cases for Multiple EDID-Like  Destinations

### ISSUE THREAD

**Issue by rbgodwin** [AMWA-TV/nmos-edid-connection-management#27]
We have identified a couple of situations where we can have multiple devices with capabilities captured in their EDIDs are present.  This issue is to track addition/development of use-cases that will allow us develop the API to support these situations.

**Comment by rbgodwin** [comment]
Simple Example for this has a HDMI-IPMX Decoder Gateway that supports multiple monitors:


Use-Case 1.1   HDMI-IPMX Gateway Displays same Received Media to Several Monitors

Prerequisites:
PR1:  An HDMI-IPMX Decoder Gateway with Multi Monitor Output Support

Steps:
ST1: IPMX Controller System establishes IS-05 Connection using steps shown in Figure 7.
ST2: IPMX Controller Adds each Display as a Destination using the IPMX Device Controller IS-EDID-CM API.
ST3: Implementation of the NMOS IPMX Device Controller sets up hardware or software to perform the necessary routing to each monitor.

Note: The NMOS Device may reject the request to display the media on a destination if it lacks capabilities or if there are incompatibilities (e.g. unable to scale).  

@N-Nagorny - Do you have another Use-Case that we could use to justify 1:N Receiver to Destination or comments on this one for our action item?

**Comment by N-Nagorny** [comment]
@rbgodwin, I'd like to clarify this use case.

I assume that the Decoder Gateway receives a single Flow and then passes it to all HDMI monitors. I see two ways to achieve that:
1. Decoder Gateway supports conversion. In this case it performs mapping from its HDMI In to HDMI Outs and has its own EDID with list of formats supported by its HDMI In. Hence, this case doesn't require Destinations because the capabilities are represented as a single Receiver with constant Receiver Caps.
2. Decoder Gateway doesn't support conversion so it should allow receiving streams supported by all monitors. As far as we still have a single Flow, we have a single Receiver so capabilities of all monitors are present with Receiver Caps of the Receiver. Hence, we should combine multiple EDIDs to a single Receiver Caps set, and from IS-05 perspective the Decoder Gateway will be a single Receiver with a single EDID. Do we want to create a dedicated API for Decoders for performing the combining and routing of a single Flow to many monitors?
